### ISSUE TITLE
bc command not available

### ISSUE THREAD

**Issue by suchitakulkarni** [scailfin/MadGraph5_aMC-NLO#46]
I was using the latest docker image to generate samples at NLO. It does not allow me the run hadronization and complains
"WARNING: bc command not available. Forbids to run the shower. please install it if you want to run the shower. (sudo apt-get install bc)" 

Can this be fixed?

**Comment by matthewfeickert** [comment]
> It does not allow me the run hadronization and complains
> "WARNING: bc command not available. Forbids to run the shower. please install it if you want to run the shower. (sudo apt-get install bc)"

Thanks for opening the Issue. :+1: Do you have a minimal reproducible example of commands to run to get this warning for testing purposed? It would be good to understand what programs in particular require it.

**Comment by suchitakulkarni** [comment]
Any NLO process generation would do. I did in interactive mode inside the docker the following

generate p p > e+ e- aEW=2 aS=0 [QCD]
output test_nlo
launch test_nlo

on the terminal you would see the warning.

**Comment by matthewfeickert** [comment]
Hm, seems that for NLO there are additional missing dependencies that I'm missing as well

```
MG5_aMC>output test_nlo
First output using loop matrix-elements has been detected. Now asking for loop reduction:
For loop computations, MadLoop requires dedicated tools to perform the reduction of loop Feynman diagrams using OPP-based and/or TIR approaches.

Which one do you want to install? (this needs to be done only once)
1. cuttools  (OPP) [0711.3596]   : will be installed (required)
2. iregi     (TIR) [1405.0301]   : will be installed (required)
3. ninja     (OPP) [1403.1229]   : will be installed (recommended)
4. collier   (TIR) [1604.06792]  : will be installed (recommended)
5. golem     (TIR) [0807.0605]   : do not install
You can:
 -> hit 'enter' to proceed
 -> type a number to cycle its options
 -> enter the following command:
    {tool_name} [install|noinstall|{prefixed_installation_path}]

If you are unsure about what this question means, just type enter to proceed.
```

**Comment by suchitakulkarni** [comment]
Right, so those dependancies can be installed 'on the fly' but not the 'bc' command since that is more native to the os itself as I understand. Thus bc is more critical I would say.

**Comment by matthewfeickert** [comment]
It seems that NLO also wants to default to HERWIG for the showering

```
The following switches determine which programs are run:
/================== Description ===================|================= values =================|============ other options =============\
| 1. Type of perturbative computation              |            order = NLO                   |     LO                                 |
| 2. No MC@[N]LO matching / event generation       |      fixed_order = OFF                   |     ON                                 |
| 3. Shower the generated events                   |           shower = HERWIG6               |     OFF|PYTHIA6Q|PYTHIA6PT|PYTHIA8     |
| 4. Decay onshell particles                       |          madspin = OFF                   |     ON|onshell                         |
| 5. Add weights to events for new hypp.           |         reweight = OFF                   |     ON|NLO|NLO_TREE|LO                 |
| 6. Run MadAnalysis5 on the events generated      |      madanalysis = Not Avail             |     Please install module              |
\======================================================================================================================================
```

PYTHIA8 is installed, so I'm not sure how critical HERWIG is here. These can get followed up on more in separate Issues.

**Comment by suchitakulkarni** [comment]
Oh wait, let me talk to NLO generation experts here. It should not want to default to HERWIG. This is definitely not the way I wanted to go  :) Let me come back on this.
