### ISSUE TITLE
Adding Delphes

### ISSUE THREAD

**Issue by surrutiaquir** [scailfin/MadGraph5_aMC-NLO#75]
First of all, thank you for doing this! I would like to ask if it is possible to include Delphes, too.

**Comment by matthewfeickert** [comment]
@surrutiaquir While I understand the interest in having access to Delphes, for this particular image I'm not interested in adding additional software for it and Delphes adds on quite a bit of size. The idea is to have much more modular images.

There is https://github.com/scailfin/delphes-python which already provides Delphes, but that repository isn't maintained anymore. Though the Dockerfiles are relatively straightforward, though admittely somewhat long, so you can probably easily build your own custom image starting from the existing images in the `FROM` field.
